codecov:
    token: 7af58a49-33fe-43f2-bf72-debfd15a19cf

codecov:
    disable_default_path_fixes: true

coverage:
    status:
        project: no
        patch: yes
        changes: no
    precision: 2
    round: down
    range: "70...100"
ignore:
    - "Pods/*"
    - "SwiftCollectionViewTests/*"

