# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'SwiftCollectionView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftCollectionView
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Swinject'
  pod 'BeerPod', :git => 'https://github.com/Pranesh-Vallabh/BeerPod.git'#'~/Documents/Libraries/BeerPod'

end

target 'SwiftCollectionViewTests' do
    pod 'Cuckoo'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'Swinject'
    pod 'BeerPod', :git => 'https://github.com/Pranesh-Vallabh/BeerPod.git'
end

target 'SwiftCollectionViewUITests' do
    pod 'Swifter'
    pod 'BeerPod', :git => 'https://github.com/Pranesh-Vallabh/BeerPod.git'
end




